### ISSUE TITLE
此插件会使频道的表情包列表变得透明

### ISSUE THREAD

**Issue by WM-wuming** [Nevodev/LL-Fluentify#2]
QQ版本: 9.9.0-14619 (64位)
![{710E483A-7583-460f-B35C-CD769C9D5729}](https://github.com/Nevodev/LL-Fluentify/assets/102670136/5822a8c0-b4b4-4ca9-9458-01995957a452)

**Comment by Nevodev** [comment]
不明原因，已去掉频道支持
