### ISSUE TITLE
最新版本不兼容轻量工具箱

### ISSUE THREAD

**Issue by KagaJiankui** [Nevodev/LL-Fluentify#4]
最新版本不兼容[轻量工具箱](https://github.com/xiyuesaves/lite_tools)，会导致轻量工具箱无法加载

**Comment by Nevodev** [comment]
最新版本指QQ，Fluentify，还是轻量工具箱？

**Comment by KagaJiankui** [comment]
轻量工具箱和LiteLoader更新最新版本之后Fluentify最新版本不兼容轻量工具箱的问题已经解决
