### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shi-an** [Nevodev/LL-Fluentify#5]
![image](https://github.com/Nevodev/LL-Fluentify/assets/79352488/75519c60-fba0-4b65-98a8-3fc1bcbaffc3)

**Comment by Nevodev** [comment]
bqqnt？

**Comment by Nevodev** [comment]
![image](https://github.com/Nevodev/LL-Fluentify/assets/51047891/7c5efcb4-1916-4b91-a2dd-0e209afb266e)
我这里无此问题。麻烦逐个开关插件调试一下？

**Comment by shi-an** [comment]
https://github.com/Nevodev/LL-Fluentify/assets/79352488/897e1597-ceb9-42a6-ab07-940de2d173a9
