### ISSUE TITLE
右键菜单和表情栏完全透明

### ISSUE THREAD

**Issue by itsHenry35** [Nevodev/LL-Fluentify#7]
<img width="342" alt="image" src="https://github.com/Nevodev/LL-Fluentify/assets/58730749/a73ef69b-417a-4787-9715-77ee844380d1">
<img width="1536" alt="image" src="https://github.com/Nevodev/LL-Fluentify/assets/58730749/91e67d9e-4fef-40c5-9d6f-83cda844bb14">
<img width="1536" alt="image" src="https://github.com/Nevodev/LL-Fluentify/assets/58730749/1f7fb884-0b21-40cd-8cac-c36ba9a520a3">
<img width="345" alt="image" src="https://github.com/Nevodev/LL-Fluentify/assets/58730749/c9644bf6-b46d-462f-b81e-ba3db1daec23">

**Comment by Nevodev** [comment]
窗口背景不能是mica，不能是acrylic，只能为不透明纯色，否则backdrop-filter不会生效
